### ISSUE TITLE
Invariant violated: no value in mreceivers for ip

### ISSUE THREAD

**Issue by Alrighttt** [ssadler/zeno#8]
`[Error] Invariant violated: no value in mreceivers for ip`

This error message can be reproduced with the following script. It is simply rapidly opening then closing sockets with the target. 

```
#!/usr/bin/env python3
import socket
import binascii

def spam(peer):
    sends = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sends.connect(peer)
    sends.close()

target = ('<target IP>', <target port>) # your target 

while True:
    spam(target)
```

**Comment by ssadler** [comment]
Good find!

**Comment by ssadler** [comment]
So I have a test case for this using an exhaustive checker, and I believe I fixed the issue, but I found an issue in the checker so I'm waiting for closure on that: https://github.com/barrucadu/dejafu/issues/323#issuecomment-639902814.
