### ISSUE TITLE
Zeno not properly closing sockets

### ISSUE THREAD

**Issue by Alrighttt** [ssadler/zeno#9]
I am seeing multiple `CLOSE_WAIT` connections in netstat from the network's seed node. 

Please see https://stackoverflow.com/questions/15912370/how-do-i-remove-a-close-wait-socket-connection for an explanation of `CLOSE_WAIT`.

These connections get stuck indefinitely until zeno is restarted. This may be related to https://github.com/ssadler/zeno/issues/8 . Please let me know if you need me to consistently reproduce this.

**Comment by ssadler** [comment]
I believe this is fixed in dev branch (will be master on Monday)
